---
title: "6372 EDA moviedata"
author: "Jonathan Tan"
date: "9/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r import}
#insert your movie database file here

mdata <- readxl::read_xlsx("D:/SMU/DS 6372 Applied Statistics/Sample Datasets/2014 and 2015 CSM dataset.xlsx")
names(mdata)[14]= "Aggregate_Followers" #the space was interfering with some loops
#names(mdata)
head(mdata)

```

```{r inital visualizations}
library(ggplot2)

ggplot(data = mdata, aes(x = Ratings, y = Gross))+
  geom_bin2d(bins = 20)+
  labs(title = "Movie Ratings VS Gross")
```

```{r vis2}
ggplot()+
  geom_histogram(data = mdata, aes(x = Screens, fill = I("Blue")), binwidth = 40)

ggplot(data = mdata, aes(x = Screens, y = Gross))+
  geom_line()
```


```{r vis3}
ggplot(data = mdata, aes(x = Budget, y = Gross, color = factor(Year)))+
  geom_line(linejoin = "round")
 
ggplot(data = mdata, aes(sample = Gross, color = Year))+
  geom_qq()

```


roughly positive correlation between gross and rating, screens obviously positively correlates with gross. 

the distribution isn't normal, lots of small presumably indie films that didn't make much gross or have many theater showings, and a few huge blockbusters


```{r prelim model1}
m1 <- lm(Gross ~ Budget + Screens, data = mdata)

summary(m1)
layout(matrix(c(1, 2, 3, 4), 2, 2)) 
plot(m1)
```

```{r prelim model2}
m2 <- lm(Gross ~ Budget + Screens + Budget*Screens, data = mdata)
#with multvar
summary(m2)
layout(matrix(c(1, 2, 3, 4), 2, 2)) 
plot(m2)
```

```{r var scatter}
varpool <- names(mdata) #varnames
varpool <- varpool[-5] #take out gross 
varpool <- varpool[-1] #take out movie name
z <- seq(1, length(varpool), 1) #number of var iterations 

i = 0
x = 0

for( i in z)
{
 x <- t(combn(varpool, i)) #generate combinations of i variables
 comboname <- paste("combos", i, sep = "") #iterative name var generation thing?
 assign(comboname, x)
}
#should generate combinations of the 13 variables in groups of 1 to 12 



```


```{r run buncha models}
#need to rotate combo lists, and through combo lists into lm formula
#gross ~ combo[i]? 

#works fine for the singular var, but how to stich the multiple model comboes into a readable formula


q = 1
comboslength <- seq(1, length(combos1), 1)
for(i in comboslength)
{
  mname <- paste("model", q, sep = "")
  
  varform <- as.formula(paste("Gross ~", combos1[i], sep = ""))
  l = lm(formula = varform, data = mdata)
  
  assign(mname, l)
  q = q+1
}

```


```{r test formula generation}
varform <- as.formula(paste("Gross ~ ", combos2[1], sep = ""))
lm(formula= varform, data = mdata)
```




















