---
title: "Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction Required

# Data Description Required

# Exploratory Analysis Required

# Addressing Objective 1:
	Restatement of Problem and the overall approach to solve it Required

## Model Selection Required
  		Type of Selection
  			Options: LASSO, RIDGE, ELASTIC NET,Stepwise, Forward, Backward, Manual / Intuition, A mix of all of the above.  	

## Checking Assumptions Required
			Residual Plots
			Influential point analysis (Cook’s D and Leverage)

## Compare Competing Models Optional (Helpful if using 2 model strategy)
			Via:  Training and test set split or CV
      Possible Metrics: (ASE, AIC, BIC, adj R2, etc)
	
##	Parameter Interpretation
		Interpretation  Required
		Confidence Intervals Required
	
## Final conclusions from the analyses of Objective 1 Required
  In addition to overall conclusions, feel free to include additional insights or concerns gleaned from the analysis.  What needs to be done next or how could we do it better next time?  

# Addressing Objective 2
  State what route you are going to take 2way ANOVA or Time series and summarize the goal.  Required

## Main Analysis Content Required
	This will depend on the route you take.  I’m leaving it open here to see what you do.

## Conclusion/Discussion Required
		The conclusion should reprise the questions and conclusions of objective 2.

# Appendix Required
	Well commented SAS/R Code Required
 	Graphics and summary tables (Can be placed in the appendix or in the written report itself.)
